/**
 * Turns the posts manifest (migration/posts-manifest.csv, spec 3.6 blog pruning) into redirect and 410
 * rows, gated on marketing's `confirmed` column: only rows marked `yes` generate anything.
 *
 * - merge + confirmed: a 301 from the post to its `target` (src/data/redirects-posts.yaml)
 * - drop + confirmed: a 410 (src/data/gone-posts.yaml; spec 3.6 "noindex or delete the frontier-technology posts")
 * - keep and review: nothing (kept posts are imported as pages; review rows need a decision first)
 *
 * A post already covered by a hand-written row in redirects.yaml or gone.yaml is left to that row.
 */
import { isExternal, matchesRule, normalizePath, type GoneRule, type RedirectRule } from '../../integrations/routes-core.ts';

export const MANIFEST_CSV = 'migration/posts-manifest.csv';
export const REDIRECTS_OUT = 'src/data/redirects-posts.yaml';
export const GONE_OUT = 'src/data/gone-posts.yaml';

export interface ManifestRow {
  path: string;
  research_class: string;
  proposed_decision: string;
  target: string;
  owner_page: string;
  reason: string;
  confirmed: string;
}

export interface GeneratedRules {
  redirects: RedirectRule[];
  gone: GoneRule[];
  /** Confirmed rows that generate nothing, with why. */
  skipped: Array<{ path: string; reason: string }>;
  /** Unusable confirmed rows (bad target, unknown decision); the generator refuses to write. */
  errors: string[];
  /** Non-blocking notes (unrecognised `confirmed` values, disagreements with the hand-written data). */
  warnings: string[];
}

/** Only an explicit yes confirms a row (case and surrounding spaces ignored). */
export function isConfirmed(value: string | undefined): boolean {
  return (value ?? '').trim().toLowerCase() === 'yes';
}

export function generatePostRules(rows: ManifestRow[], existing: { redirects: RedirectRule[]; gone: GoneRule[] }): GeneratedRules {
  const out: GeneratedRules = { redirects: [], gone: [], skipped: [], errors: [], warnings: [] };
  const seen = new Set<string>();

  for (const row of rows) {
    const path = normalizePath(row.path);
    const decision = row.proposed_decision.trim().toLowerCase();
    const confirmedValue = row.confirmed.trim();
    if (!isConfirmed(confirmedValue)) {
      if (confirmedValue && confirmedValue.toLowerCase() !== 'no') {
        out.warnings.push(`${path}: confirmed="${confirmedValue}" is not understood; only "yes" confirms a row`);
      }
      continue;
    }
    if (seen.has(path)) {
      out.errors.push(`${path}: listed twice in the manifest`);
      continue;
    }
    seen.add(path);

    if (decision === 'keep' || decision === 'review') {
      out.skipped.push({ path, reason: `${decision}: generates nothing` });
      continue;
    }
    if (decision !== 'merge' && decision !== 'drop') {
      out.errors.push(`${path}: unknown decision "${row.proposed_decision}" (expected keep, merge, drop or review)`);
      continue;
    }

    const handRedirect = existing.redirects.find((r) => matchesRule(path, r.from, r.match));
    const handGone = existing.gone.find((g) => matchesRule(path, g.path, g.match));
    if (handRedirect || handGone) {
      const by = handRedirect ? `redirects.yaml (${handRedirect.from} -> ${handRedirect.to})` : `gone.yaml (${handGone!.path})`;
      out.skipped.push({ path, reason: `already covered by ${by}` });
      const agrees = decision === 'merge' ? handRedirect && normalizePath(handRedirect.to) === normalizePath(row.target) : Boolean(handGone);
      if (!agrees) out.warnings.push(`${path}: manifest says ${decision}${decision === 'merge' ? ` to ${row.target}` : ''}, but ${by} wins; align one of them`);
      continue;
    }

    if (decision === 'drop') {
      out.gone.push({ path, note: 'posts manifest: drop (confirmed)' });
      continue;
    }
    const target = row.target.trim();
    if (!target.startsWith('/') && !isExternal(target)) {
      out.errors.push(`${path}: merge target "${row.target}" is not a path`);
      continue;
    }
    if (normalizePath(target) === path) {
      out.errors.push(`${path}: merge target is the post itself`);
      continue;
    }
    out.redirects.push({ from: path, to: isExternal(target) ? target : normalizePath(target), note: 'posts manifest: merge (confirmed)' });
  }

  const byPath = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
  out.redirects.sort((a, b) => byPath(a.from, b.from));
  out.gone.sort((a, b) => byPath(a.path, b.path));
  return out;
}

/** A YAML scalar: plain when it is a simple path or slug, JSON-quoted (valid YAML) otherwise. */
const scalar = (value: string) => (/^[A-Za-z0-9/._-]+$/.test(value) ? value : JSON.stringify(value));

const header = (what: string) =>
  [
    `# GENERATED by scripts/posts-redirects.ts from ${MANIFEST_CSV}. Do not edit by hand.`,
    '# Regenerate after marketing updates the manifest: node scripts/posts-redirects.ts',
    `# Lists ${what} for manifest rows with confirmed=yes only (spec 3.6). Keep and review rows generate nothing.`,
    '',
  ].join('\n');

export function renderRedirectsYaml(rules: RedirectRule[]): string {
  const rows = rules.map((r) => `- { from: ${scalar(r.from)}, to: ${scalar(r.to)}${r.note ? `, note: ${scalar(r.note)}` : ''} }`);
  return `${header('a 301 to the merge target')}${rows.length ? rows.join('\n') : '[]'}\n`;
}

export function renderGoneYaml(rules: GoneRule[]): string {
  const rows = rules.map((g) => `- { path: ${scalar(g.path)}${g.note ? `, note: ${scalar(g.note)}` : ''} }`);
  return `${header('a 410 Gone for each dropped post')}${rows.length ? rows.join('\n') : '[]'}\n`;
}
